### ISSUE TITLE
Hi，A function problem about the Plugin

### ISSUE THREAD

**Issue by CoresenYan** [nzbin/magnify#1]
The magnfiy is a great plugin!  I have a problem:  I use the magnify to open a photo , but when I close the magnify , the backspace and F1-F12 is not available, so I must be refresh the father html... In my opinion, when we close the magnify, backspace and F1-F12 should be remove disable.
As i see, your home page of the maginfy function show also have the problem.

**Comment by nzbin** [comment]
@githubygq Thanks for your question, I have fixed it.
