### ISSUE TITLE
同样在IE11下，为什么旋转图片等按钮无法使用？

### ISSUE THREAD

**Issue by gaosuhui** [nzbin/magnify#11]
我使用ie11在我的电脑上调试没什么问题，但是在别的电脑上访问时，同样是IE11,图片底下的一排按钮失去作用，图片放大缩小，旋转都无效，切鼠标移动至小图标时也无反应。请指点。

**Comment by nzbin** [comment]
请确认是否设置了文档模式，插件对 IE11 是支持的，对于这种问题不太好确定。

**Comment by gaosuhui** [comment]
https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css
https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css
https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js
https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js
这几个文件都在服务器端，需要联网才能访问，非网络环境下如何使用？

**Comment by nzbin** [comment]
@gaosuhui 非网络环境可以下载到本地
