### ISSUE TITLE
关于Magnify的groupIndex属性问题

### ISSUE THREAD

**Issue by BestPei** [nzbin/magnify#15]
无论是使用changed回调还是beforeChanged回调，为何Magnify的groupIndex属性总是指向下一个图片的位置？且同一group的多张图片，Magnify的$el属性总是指向第一张图片的位置。那请问如何在beforeChanged的时候获得当前图片的dom？

**Comment by BestPei** [comment]
![Uploading image.png…]()

**Comment by BestPei** [comment]
![image](https://user-images.githubusercontent.com/26396103/49558603-98b7a800-f946-11e8-8cec-6395ce29ffc4.png)

**Comment by nzbin** [comment]
@BestPei 这个钩子确实有一点问题，已经修复。另外可以具体说一下你的需求

**Comment by BestPei** [comment]
@nzbin 感谢回复！

我是想做一个在图片旋转后可以自动保存旋转角度的功能，目前单图片保存旋转角度已经实现了，在做 
多图片旋转保存的时候我试图通过每次点击切换图片按钮时保存旋转角度的方式去做，但是在获取当前图片dom的时候遇到了此问题

**Comment by BestPei** [comment]
@nzbin 感谢更新！

beforeChange和changed回调中的index参数已经可以正常使用！虽然Magnify.groupIndex在这两个回调里仍然指向的是下一个图片的下标，但至少在beforeClose回调里是正常的，通过这三个回调我已经完成了查看一组图片时保存图片旋转角度的功能！再次感谢！
