### ISSUE TITLE
可否在全屏状态下仍然显示工具条？ 

### ISSUE THREAD

**Issue by JtCheung** [nzbin/magnify#17]
请问是否可以增加一项配置，在全屏状态下显示工具栏。
例如：在全屏状态下当用户移动鼠标的时候显示工具条，一段时间后隐藏，或者当用户将鼠标移到工具栏位置的时候显示。🎉🎉🎉

**Comment by nzbin** [comment]
可以的，目前在全屏模式隐藏了工具栏

**Comment by JtCheung** [comment]
谢谢！:smile::smile:
