### ISSUE TITLE
底部小图预览功能，点击小图可切换到大图

### ISSUE THREAD

**Issue by kleen** [nzbin/magnify#18]
![image](https://user-images.githubusercontent.com/3284413/55850476-08ed6900-5b87-11e9-88c5-0daff04fa641.png)
项目实际需要，可能会有多个图片,给一个查看图片按钮,  点击弹出类似这样的

**Comment by nzbin** [comment]
@kleen 该插件目前不具备小图预览功能，可以通过钩子函数手动添加

**Comment by nzbin** [comment]
可以通过自定义功能实现，请参考这个例子 https://codepen.io/nzbin/pen/KKrOPKE
