### ISSUE TITLE
Image rotation doesn't work on chrome

### ISSUE THREAD

**Issue by usmanusn47** [nzbin/magnify#19]
Images are not rotating on chrome unless press Crlt+F5.

**Comment by nzbin** [comment]
@usmanusn47  I can't repeat it

**Comment by usmanusn47** [comment]
> 
> 
> @usmanusn47 I can't repeat it

**Comment by usmanusn47** [comment]
> 
> 
> @usmanusn47 I can't repeat it

Chrome cached image so add query string in url work for me. Thanks for awesome plugin
