### ISSUE TITLE
IE8的兼容性问题

### ISSUE THREAD

**Issue by tubugs** [nzbin/magnify#2]
IE8的旋转存在兼容性问题

**Comment by nzbin** [comment]
@tubugs  你好，我新建了一个仓库 [magnify-lower](https://github.com/nzbin/magnify-lower) ，它支持 IE9 以下版本，需要引用 [jqueryrotate.js](https://github.com/wilq32/jqueryrotate) ，虽然解决了功能的兼容性，但在低版本 IE 中会有一些性能问题，整体而言可以满足基本的图片查看需求。
