### ISSUE TITLE
Print Functionality

### ISSUE THREAD

**Issue by csandreas1** [nzbin/magnify#20]
Hello, this is not an issue, i just want implement print functionality for each image.

I am using this jQuery plugin:
https://github.com/DoersGuild/jQuery.print

So for each image i should use something like:

```
$("#myElementId").print({
  globalStyles: true,
  mediaPrint: false,
  stylesheet: null,
  noPrintSelector: ".no-print",
  iframe: true,
  append: null,
  prepend: null,
  manuallyCopyFormValues: true,
  deferred: $.Deferred(),
  timeout: 750,
  title: null,
  doctype: '<!doctype html>'
});
```

**Comment by nzbin** [comment]
In fact, I don't want to add functions any more. Maybe I will add it a few days. Now I put more attention to [photoviewer](https://github.com/nzbin/photoviewer).  You can try it.

**Comment by nzbin** [comment]
V1.6.0 has support custom buttons, you can add a custom print button.
Demo: [Custom Print Button](https://codepen.io/nzbin/pen/XWdPLVa)
