### ISSUE TITLE
无法正常缩放和拖动

### ISSUE THREAD

**Issue by Qiyue0726** [nzbin/magnify#25]
![image](https://user-images.githubusercontent.com/33934935/87284479-ff407700-c528-11ea-86b1-bb468d47c00b.png)
滚轮滑动一下就会出现这种情况，无法继续放大，拖动也只能上下拖动，无法左右

**Comment by nzbin** [comment]
看一下控制台有没有报错，确认使用方式是否正确，如果有在线例子的话比较容易诊断
