### ISSUE TITLE
You can open an image repeatedly, and it creates new DOM elements that overlap the old

### ISSUE THREAD

**Issue by catmeme** [nzbin/magnify#3]
### Steps to reproduce

1. Go to the demo page: https://nzbin.github.io/magnify/
2. Click the first image multiple times
3. Click close once

### Result

You will see the image (or copies of the image) are open multiple times under the one closed.

### Expected Result

One modal per image.

**Comment by nzbin** [comment]
@catmeme Yep, it supports multiple instances, if you want just single instance, you can set the option`multiInstances: false` . 
[Live demo on CodePen](https://codepen.io/nzbin/pen/zRYXEd)
