### ISSUE TITLE
How can support touch to zoom in and zoom out on mobile?

### ISSUE THREAD

**Issue by MaxWMChen** [nzbin/magnify#41]
Hello, I try the demo (https://nzbin.github.io/magnify/) use mobile, any fuction is worked but touch to zoom in  and zoom out not working. And zoom in button and zoom out button can work. Can you hlep me? Thank you so much.

**Comment by nzbin** [comment]
I'm sorry, this plugin is designed for PC, it may not perform well on mobile.
