### ISSUE TITLE
Auto loading of images and thumbnails

### ISSUE THREAD

**Issue by gkreddy** [nzbin/magnify#6]
is it possible to load next images automatically without clicking on next buttons?. is there any provision to add thumbnails instead of large images? say for eg. initially we load only thumbnails (images with small size) when the image open in modal (or when user clicks on image) it should open large image

**Comment by nzbin** [comment]
@gkreddy Thanks for your suggestions, I will add the the features for next version. But I'm sorry, I don't quite understand what you said about the thumbnails?
