### ISSUE TITLE
发现一个问题，就是每点击一次图片会创建一次magnify-modal层

### ISSUE THREAD

**Issue by xiaochegnzi0** [nzbin/magnify#7]
如题，点击不同图片时，会显示出多个magnify-modal层

**Comment by nzbin** [comment]
@xiaochegnzi0 #3 只显示一个弹层，需要设置 `multiInstance: false`，文档页面可以测试参数

**Comment by jiuyuehe** [comment]
好用，有没有 react 版本 或者angularjs 版本的呢？

**Comment by nzbin** [comment]
@jiuyuehe 请持续关注更新动态，最近在忙其它的项目，react 及其它版本将尽快发布!

**Comment by jiuyuehe** [comment]
@nzbin  辛苦辛苦！
