### ISSUE TITLE
如何在已经显示的图片的情况下，修改图片

### ISSUE THREAD

**Issue by jiuyuehe** [nzbin/magnify#8]
在预览图片的时候需要查看原图， 默认是压缩过的图。 如何增加一个按钮，点击后将图片修改为原图链接呢？

感谢

**Comment by nzbin** [comment]
@jiuyuehe 不太懂你的意思，缩略图链接和原图链接不就是分开的吗？

**Comment by jiuyuehe** [comment]
就是照片很大， 有多张缩略图， 图标显示  45*45  的缩略图，打开 显示   800*800  的缩略图 ，这里需要增加一个原图按钮， 查看 1600*1600 的图

@nzbin  明白吗？

**Comment by nzbin** [comment]
@jiuyuehe 可以参考一下这个 [CodePen](https://codepen.io/nzbin/pen/VXoYEg)

**Comment by jiuyuehe** [comment]
感谢啦 @nzbin

**Comment by vmto** [comment]
这样的场景可以实现吗：一个叫作[查看图片]的按钮，点开之后是一组图片可以左右切换，这样做的目的是纯文字排版、节省空间。data-group文档上不详细，请赐教~

**Comment by nzbin** [comment]
@vmto 感谢反馈，暂时不支持这样做，但是实现并不难，如果能看懂源码的话，可以 fork 一份，直接在源码上修改。该项目设计之初考虑的是简单直接，所以缺少了一些灵活性。这个项目不会再做大的修改，感兴趣的话可以关注一下这个项目的升级版 [photoviewer](https://github.com/nzbin/photoviewer)

**Comment by vmto** [comment]
@nzbin 谢谢！
琢磨了一下，实现了：
```bash
<#list (pictures) as list>
  <#if list_index==0>
    <a data-magnify="gallery" href="${URL}${(list.path)}">查看图片</a>
  </#if>
    <a data-magnify="gallery" href="${URL}${(list.path)}"></a>
</#list>
```

**Comment by nzbin** [comment]
查看大图最好的方式是在标题处添加 `查看大图` 链接
https://codepen.io/nzbin/pen/zyOLwr
