### ISSUE TITLE
添加一个功能 magnify-modal 随 magnify-images 一同缩放

### ISSUE THREAD

**Issue by benmo1602** [nzbin/magnify#9]
magnify-modal 随 magnify-images 一同缩放

$image.css({
width: Math.round(newWidth) + 'px',
height: Math.round(newHeight) + 'px',
left: 0,
top: 0
});

// 此处为 需求添加 demo 
var $pimage = $image.parents('.magnify-modal');
$pimage.css({
width: Math.round(newWidth) + 'px',
height: Math.round(newHeight) + 'px',
left: $pimage.position().left + Math.round(newLeft) + 'px',
top: $pimage.position().top + Math.round(newTop) + 'px' 
})

**Comment by nzbin** [comment]
@caokunyu 请参考其它类似项目
